import { Geist } from "next/font/google";
import "./globals.css";
import AosProvider from "@/provider/AosProvider";

const geistSans = Geist({
  variable: "--font-geist",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} font-geist bg-black`}>
        <AosProvider>{children}</AosProvider>
      </body>
    </html>
  );
}
